services:
  my-mvc-web:
    image: my-mvc-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_mvc_container
    restart: always
    ports:
      - "5006:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production